spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/event_app
    username: event_app
    password: event_app
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none  # Disable Hibernate auto DDL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  mail:
    host: smtp.gmail.com
    port: 587
    username: "tmcolab1@gmail.com"
    password: "zqts lviq fekp muxf"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  logging:
    level:
      org:
        springframework: DEBUG
      com:
        tharanga: DEBUG


project:
  event: event/

base:
  url: "http://localhost:8080"